stages:
  - deploy


pages:
  stage: deploy
  script:
  - cd docs
  - yarn install
  - yarn build
  - mv ./build ../public
  artifacts:
    paths:
    - public
    expire_in: 1 hour
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    # Allow deploy documentation changes from a MR
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual

